# Generated by Django 4.1.2 on 2023-04-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('curso_concretado', models.CharField(max_length=40)),
                ('resenia', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
